name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --tag heonie/docker-react-template -f Dockerfile.dev .
      - name: Run the Docker image and do the test
        run: docker run -e CI=true heonie/docker-react-template npm run test -- --coverage
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react-app
          environment_name: Dockerreactapp-env
          version_label: 12345
          region: ap-northeast-2
          deployment_package: deploy.zip
      - run: echo "🍏 This job's status is ${{ job.status }}."
